### ISSUE TITLE
Deleting undone tasks not working

### ISSUE THREAD

**Issue by Blizzrd003** [dyankristoper/svelte-todo-app#11]
Some tasks are having issues with the delete button. A page refresh is needed to continue with the delete function. Possible delay only as task 2 gets deleted after a while.

https://www.loom.com/share/b4fab01479b74d93b4fbf2945405cad0

Also, a different task is sometimes deleted. 
@00:04, delete task 4 button was clicked but task 1 got deleted.
@00:28, delete task 3 button was clicked but task 2 got deleted.

https://www.loom.com/share/cae1712970944aeca7dc8be5ee9b04b9

**Comment by dyankristoper** [comment]
@Blizzrd003 For testing

**Comment by Blizzrd003** [comment]
Delete task is now working correctly. Closing issue.
