### ISSUE TITLE
Marking tasks as done and deleting creates undefined entries

### ISSUE THREAD

**Issue by Blizzrd003** [dyankristoper/svelte-todo-app#12]
After marking a task as done and deleting it, clicking "Mark as done" on another tasks creates an undefined task (done).

Same thing happens when a task is deleted first, then another task is marked as done. Also creates an undefined entry.

![image](https://user-images.githubusercontent.com/77159976/237013550-22204a71-88d3-466f-bac7-d48d4e94ebe4.png)

https://www.loom.com/share/570e613acce94ddeb13e9471e2a88ace

**Comment by dyankristoper** [comment]
@Blizzrd003 For Testing

**Comment by dyankristoper** [comment]
@Blizzrd003 For testing

**Comment by Blizzrd003** [comment]
No more undefined entry. Closing issue.
