### ISSUE TITLE
Page not scrollable and no sorting (optional)

### ISSUE THREAD

**Issue by Blizzrd003** [dyankristoper/svelte-todo-app#9]
Page is not scrollable after adding multiple tasks and entries have no sorting.

![image](https://user-images.githubusercontent.com/77159976/237009384-8be0c53e-ce1d-40f2-a472-3d6844b7a533.png)

**Comment by dyankristoper** [comment]
@Blizzrd003 For Testing

**Comment by Blizzrd003** [comment]
![image](https://github.com/dyankristoper/svelte-todo-app/assets/77159976/6a71d0e4-25f1-4aca-ad7b-b1cf33b55bdd)

Still not scrollable and no sorting

**Comment by Blizzrd003** [comment]
Page is now scrollable.

**Comment by Blizzrd003** [comment]
Sorting by creation date is now live. Closing issue.
